python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool lsio_trigger_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool lsio_trigger_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_watermark_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_watermark_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_empty_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_empty_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_watermark_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_watermark_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_done_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_tx_done_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_overflow_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_overflow_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_frame_err_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_frame_err_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_break_err_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_break_err_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_timeout_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_timeout_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_parity_err_o" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "bool intr_rx_parity_err_o" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int32_t hw2reg_intr_state" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int32_t hw2reg_intr_state" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_status" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_status" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_fifo_status" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_fifo_status" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_fifo_ctrl" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_fifo_ctrl" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_rdata" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int8_t hw2reg_rdata" "0"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int16_t hw2reg_val" "1"
python3 $ACEROOT/src/DU_gen/DT_gen.py ../1_csv/processed_uart_filtered.csv "int16_t hw2reg_val" "0"



#python3 $ACEROOT/Detection_trace_gen/DU_gen.py uart_filtered_fault_done0.csv ../1_csv/processed_uart_filtered.csv --signal-col "uint_64t done" processed_uart_filtered --output "./Detection_traces/uart_filtered_fault_done0_DU.csv"
#python3 $ACEROOT/Detection_trace_gen/DU_gen.py uart_filtered_fault_done1.csv ../1_csv/processed_uart_filtered.csv --signal-col "uint_64t done" processed_uart_filtered --output "./Detection_traces/uart_filtered_fault_done1_DU.csv"

