// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef SQRT_CALCULATOR_HH
#define SQRT_CALCULATOR_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "hif_globals.hpp"
#include "muffin/FaultNode.hpp"
#include "muffin/muffin_dataTypes.hpp"

class sqrt_calculator
{

public:

    muffin::FaultNode hif_fault_node;
    uint16_t in_old;
    bool start_old;
    bool rst_old;
    bool clk_old;
    struct sqrt_calculator_iostruct{
        bool clk;
        bool rst;
        bool start;
        uint16_t in;
        uint8_t out;
        bool error;
        bool done;

        sqrt_calculator_iostruct():
            clk(false),
            rst(false),
            start(false),
            in(uint16_t(0U)),
            out(uint8_t(0U)),
            error(false),
            done(false)
        {}

        sqrt_calculator_iostruct( const bool clk_0, const bool rst_0, const bool
             start_0, const uint16_t in_0, const uint8_t out_0, const bool error_0,
             const bool done_0 ):
            clk(clk_0),
            rst(rst_0),
            start(start_0),
            in(in_0),
            out(out_0),
            error(error_0),
            done(done_0)
        {}

        ~sqrt_calculator_iostruct()
        {}

        bool operator == (const sqrt_calculator_iostruct & other) const
        {
            if (clk != other.clk) return false;
            if (rst != other.rst) return false;
            if (start != other.start) return false;
            if (in != other.in) return false;
            if (out != other.out) return false;
            if (error != other.error) return false;
            if (done != other.done) return false;
            return true;
        }
    };
    sqrt_calculator_iostruct hif_a2t_data;
    uint16_t num;
    uint8_t guess;
    uint8_t iter;
    sqrt_calculator();


    ~sqrt_calculator();


    uint16_t num_new;
    uint8_t guess_new;
    uint8_t iter_new;
    bool process_in_queue;
    bool flag_process_executed;
    bool flag_pos_clk;
    bool flag_pos_rst;

    void process();


    void update_input_queue( bool synch_phase = true );


    void update_event_queue();


    void flag_elaboration();


    void synch_elaboration();


    void simulate( sqrt_calculator_iostruct * io_exchange, int32_t & cycles_number
         );


    void start_of_simulation();


    void initialize();


    void finalize();


private:

    sqrt_calculator( const sqrt_calculator & );
    const sqrt_calculator& operator= ( const sqrt_calculator & );


};


#endif

